-- Adminer 4.8.1 PostgreSQL 16.4 (Debian 16.4-1.pgdg120+2) dump

\connect "hamza";

DROP TABLE IF EXISTS "api_archived_candidat";
CREATE TABLE "public"."api_archived_candidat" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "CV_Link" character varying(255),
    "datenaissance" date,
    "age" integer,
    "certificat" jsonb[] NOT NULL,
    "client_id" character varying(255),
    "created_at" timestamptz,
    "domain" character varying(254)[],
    "education" jsonb[] NOT NULL,
    "email" character varying(254),
    "embedding" vector(384),
    "embedding_cohere" vector(4096),
    "experience" jsonb[] NOT NULL,
    "file_name" character varying(255),
    "first_id" integer NOT NULL,
    "formation" jsonb[] NOT NULL,
    "langues" character varying(255)[] NOT NULL,
    "linkedin_url" character varying(255),
    "nbrexp" double precision,
    "nom" character varying(50),
    "pays_de_residence" character varying(255),
    "phone" character varying(254),
    "poste_actuelle" character varying(255),
    "sexe" character varying(255),
    "skills" jsonb[] NOT NULL,
    "source" character varying(30),
    CONSTRAINT "api_archived_candidat_id_client_id_0ce7d1a4_uniq" UNIQUE ("id", "client_id"),
    CONSTRAINT "api_archived_candidat_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "api_candidat";
CREATE TABLE "public"."api_candidat" (
    "id_candidat" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nom" character varying(50),
    "file_name" character varying(255),
    "email" character varying(254),
    "phone" character varying(254),
    "domain" character varying(254)[],
    "datenaissance" date,
    "age" integer,
    "sexe" character varying(255),
    "pays_de_residence" character varying(255),
    "poste_actuelle" character varying(255),
    "nbrexp" double precision,
    "skills" jsonb[] NOT NULL,
    "certificat" jsonb[] NOT NULL,
    "experience" jsonb[] NOT NULL,
    "formation" jsonb[] NOT NULL,
    "education" jsonb[] NOT NULL,
    "langues" character varying(255)[] NOT NULL,
    "linkedin_url" character varying(255),
    "source" character varying(30),
    "status" character varying(30) NOT NULL,
    "embedding" vector(384),
    "embedding_cohere" vector(4096),
    "CV_Link" character varying(255),
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "client_id" character varying(255),
    "archived_id" integer,
    CONSTRAINT "api_candidat_id_candidat_client_id_4e11173f_uniq" UNIQUE ("id_candidat", "client_id"),
    CONSTRAINT "api_candidat_pkey" PRIMARY KEY ("id_candidat")
) WITH (oids = false);


DROP TABLE IF EXISTS "api_candidathascertificat";
CREATE TABLE "public"."api_candidathascertificat" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "date_obtention" character varying(255),
    "date_expiration" character varying(255),
    "id_candidat" integer NOT NULL,
    "id_certificat" integer NOT NULL,
    CONSTRAINT "api_candidathascertifica_id_candidat_id_certifica_74e14a6f_uniq" UNIQUE ("id_candidat", "id_certificat"),
    CONSTRAINT "api_candidathascertificat_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "api_candidathascertificat_id_candidat_377eaed7" ON "public"."api_candidathascertificat" USING btree ("id_candidat");

CREATE INDEX "api_candidathascertificat_id_certificat_f1c90784" ON "public"."api_candidathascertificat" USING btree ("id_certificat");


DROP TABLE IF EXISTS "api_candidathasdomaine";
CREATE TABLE "public"."api_candidathasdomaine" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_candidat" integer NOT NULL,
    "id_domaine" integer NOT NULL,
    CONSTRAINT "api_candidathasdomaine_id_candidat_id_domaine_06eb0561_uniq" UNIQUE ("id_candidat", "id_domaine"),
    CONSTRAINT "api_candidathasdomaine_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "api_candidathasdomaine_id_candidat_2afb0b54" ON "public"."api_candidathasdomaine" USING btree ("id_candidat");

CREATE INDEX "api_candidathasdomaine_id_domaine_f4c88203" ON "public"."api_candidathasdomaine" USING btree ("id_domaine");


DROP TABLE IF EXISTS "api_candidathaseducation";
CREATE TABLE "public"."api_candidathaseducation" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "date_obtention" character varying(255),
    "id_candidat" integer NOT NULL,
    "id_education" integer NOT NULL,
    CONSTRAINT "api_candidathaseducation_id_candidat_id_education_9b8a99d8_uniq" UNIQUE ("id_candidat", "id_education"),
    CONSTRAINT "api_candidathaseducation_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "api_candidathaseducation_id_candidat_19931e11" ON "public"."api_candidathaseducation" USING btree ("id_candidat");

CREATE INDEX "api_candidathaseducation_id_education_8cbbfbe8" ON "public"."api_candidathaseducation" USING btree ("id_education");


DROP TABLE IF EXISTS "api_candidathasformation";
CREATE TABLE "public"."api_candidathasformation" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_candidat" integer NOT NULL,
    "id_formation" integer NOT NULL,
    CONSTRAINT "api_candidathasformation_id_candidat_id_formation_3859532c_uniq" UNIQUE ("id_candidat", "id_formation"),
    CONSTRAINT "api_candidathasformation_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "api_candidathasformation_id_candidat_f0dcb740" ON "public"."api_candidathasformation" USING btree ("id_candidat");

CREATE INDEX "api_candidathasformation_id_formation_ccc859a3" ON "public"."api_candidathasformation" USING btree ("id_formation");


DROP TABLE IF EXISTS "api_candidathaslangue";
CREATE TABLE "public"."api_candidathaslangue" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_candidat" integer NOT NULL,
    "id_langue" integer NOT NULL,
    CONSTRAINT "api_candidathaslangue_id_candidat_id_langue_74d95a97_uniq" UNIQUE ("id_candidat", "id_langue"),
    CONSTRAINT "api_candidathaslangue_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "api_candidathaslangue_id_candidat_e6b042c1" ON "public"."api_candidathaslangue" USING btree ("id_candidat");

CREATE INDEX "api_candidathaslangue_id_langue_c90e0d1f" ON "public"."api_candidathaslangue" USING btree ("id_langue");


DROP TABLE IF EXISTS "api_candidathasskills";
CREATE TABLE "public"."api_candidathasskills" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_candidat" integer NOT NULL,
    "id_skills" integer NOT NULL,
    CONSTRAINT "api_candidathasskills_id_candidat_id_skills_aac72410_uniq" UNIQUE ("id_candidat", "id_skills"),
    CONSTRAINT "api_candidathasskills_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "api_candidathasskills_id_candidat_97c63b55" ON "public"."api_candidathasskills" USING btree ("id_candidat");

CREATE INDEX "api_candidathasskills_id_skills_f610e66e" ON "public"."api_candidathasskills" USING btree ("id_skills");


DROP TABLE IF EXISTS "api_certificat";
CREATE TABLE "public"."api_certificat" (
    "id_certificat" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nom_certificat" character varying(255),
    "domaine" character varying(255),
    "duree" character varying(255),
    "organisation" character varying(255),
    CONSTRAINT "api_certificat_nom_certificat_domaine_d_bdbaa2b4_uniq" UNIQUE ("nom_certificat", "domaine", "duree", "organisation"),
    CONSTRAINT "api_certificat_pkey" PRIMARY KEY ("id_certificat")
) WITH (oids = false);


DROP TABLE IF EXISTS "api_domaine";
CREATE TABLE "public"."api_domaine" (
    "id_domaine" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nom_domaine" character varying(255),
    "client_id" character varying(255),
    CONSTRAINT "api_domaine_nom_domaine_key" UNIQUE ("nom_domaine"),
    CONSTRAINT "api_domaine_pkey" PRIMARY KEY ("id_domaine")
) WITH (oids = false);

CREATE INDEX "api_domaine_nom_domaine_3e0e5fc7_like" ON "public"."api_domaine" USING btree ("nom_domaine");


DROP TABLE IF EXISTS "api_education";
CREATE TABLE "public"."api_education" (
    "id_education" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nom_ecole" character varying(255),
    "nom_diplome" character varying(255),
    "type_diplome" character varying(255),
    "specialite" character varying(255),
    CONSTRAINT "api_education_nom_ecole_nom_diplome_ty_d449bbc8_uniq" UNIQUE ("nom_ecole", "nom_diplome", "type_diplome", "specialite"),
    CONSTRAINT "api_education_pkey" PRIMARY KEY ("id_education")
) WITH (oids = false);


DROP TABLE IF EXISTS "api_expprof";
CREATE TABLE "public"."api_expprof" (
    "id_exp" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "date" character varying(255),
    "titre_prof" character varying(255),
    "nom_societe" character varying(255),
    "poste" character varying(255),
    "description" text,
    "technos" character varying(255),
    "id_candidat" integer NOT NULL,
    CONSTRAINT "api_expprof_date_titre_prof_nom_soci_cee823f9_uniq" UNIQUE ("date", "titre_prof", "nom_societe", "poste", "description", "technos"),
    CONSTRAINT "api_expprof_pkey" PRIMARY KEY ("id_exp")
) WITH (oids = false);

CREATE INDEX "api_expprof_id_candidat_22fc432a" ON "public"."api_expprof" USING btree ("id_candidat");


DROP TABLE IF EXISTS "api_formation";
CREATE TABLE "public"."api_formation" (
    "id_formation" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nom_formation" character varying(255),
    "Duree_formation" character varying(255),
    CONSTRAINT "api_formation_nom_formation_Duree_formation_731fb373_uniq" UNIQUE ("nom_formation", "Duree_formation"),
    CONSTRAINT "api_formation_pkey" PRIMARY KEY ("id_formation")
) WITH (oids = false);


DROP TABLE IF EXISTS "api_job";
CREATE TABLE "public"."api_job" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "file_name" character varying(255),
    "destination" character varying(55),
    "insertion_date" date NOT NULL,
    "job_Link" character varying(255),
    "job_status" character varying(30) NOT NULL,
    "embedding" vector(384),
    "client_id" character varying(255),
    "description" text,
    "note" text,
    "start_date" date,
    "target_client_id" integer,
    "location" character varying(55),
    "salaire_maximum" double precision,
    "salaire_minimum" double precision,
    CONSTRAINT "api_job_file_name_destination_client_id_35f0c00c_uniq" UNIQUE ("file_name", "destination", "client_id"),
    CONSTRAINT "api_job_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "api_job_target_client_id_99ae746e" ON "public"."api_job" USING btree ("target_client_id");


DROP TABLE IF EXISTS "api_langue";
CREATE TABLE "public"."api_langue" (
    "id_langue" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nom_langue" character varying(255),
    CONSTRAINT "api_langue_nom_langue_key" UNIQUE ("nom_langue"),
    CONSTRAINT "api_langue_pkey" PRIMARY KEY ("id_langue")
) WITH (oids = false);

CREATE INDEX "api_langue_nom_langue_98e5d96b_like" ON "public"."api_langue" USING btree ("nom_langue");


DROP TABLE IF EXISTS "api_linkedinprofile";
CREATE TABLE "public"."api_linkedinprofile" (
    "id_profile" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "keywords" character varying(200),
    "url" character varying(5000),
    "client_id" character varying(255),
    CONSTRAINT "api_linkedinprofile_id_profile_client_id_d116866a_uniq" UNIQUE ("id_profile", "client_id"),
    CONSTRAINT "api_linkedinprofile_pkey" PRIMARY KEY ("id_profile")
) WITH (oids = false);


DROP TABLE IF EXISTS "api_matching";
CREATE TABLE "public"."api_matching" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "similarity_score" double precision NOT NULL,
    "favori" boolean NOT NULL,
    "rh" character varying(55) NOT NULL,
    "technique" character varying(55) NOT NULL,
    "test_technique" character varying(55) NOT NULL,
    "dg" character varying(55) NOT NULL,
    "note_dg" text,
    "client_id" character varying(255),
    "id_candidat_id" integer NOT NULL,
    "id_job_id" integer NOT NULL,
    "note_rh" text,
    "note_technique" text,
    "note_test_technique" text,
    CONSTRAINT "api_matching_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "unique_matching" UNIQUE ("id_candidat_id", "id_job_id", "client_id")
) WITH (oids = false);

CREATE INDEX "api_matching_id_candidat_id_b3af4aaa" ON "public"."api_matching" USING btree ("id_candidat_id");

CREATE INDEX "api_matching_id_job_id_d7c43168" ON "public"."api_matching" USING btree ("id_job_id");


DROP TABLE IF EXISTS "api_skills";
CREATE TABLE "public"."api_skills" (
    "id_skills" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nom_skills" character varying(255),
    "type_skills" character varying(255),
    CONSTRAINT "api_skills_nom_skills_key" UNIQUE ("nom_skills"),
    CONSTRAINT "api_skills_pkey" PRIMARY KEY ("id_skills")
) WITH (oids = false);

CREATE INDEX "api_skills_nom_skills_dd652692_like" ON "public"."api_skills" USING btree ("nom_skills");


DROP TABLE IF EXISTS "api_targetclient";
CREATE TABLE "public"."api_targetclient" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nom_client" character varying(255),
    "adresse" text,
    "ville" character varying(255),
    "code_postale" integer NOT NULL,
    "numero_fiscale" character varying(255),
    "telephone" integer NOT NULL,
    "mobile" integer NOT NULL,
    "courriel" character varying(254),
    "site_web" character varying(254),
    "langue" character varying(254),
    "client_id" character varying(255),
    CONSTRAINT "api_targetclient_nom_client_key" UNIQUE ("nom_client"),
    CONSTRAINT "api_targetclient_numero_fiscale_key" UNIQUE ("numero_fiscale"),
    CONSTRAINT "api_targetclient_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "api_targetclient_nom_client_eb6bf9b8_like" ON "public"."api_targetclient" USING btree ("nom_client");

CREATE INDEX "api_targetclient_numero_fiscale_a31de08c_like" ON "public"."api_targetclient" USING btree ("numero_fiscale");


DROP TABLE IF EXISTS "api_user";
CREATE TABLE "public"."api_user" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "password" character varying(128) NOT NULL,
    "last_login" timestamptz,
    "is_superuser" boolean NOT NULL,
    "username" character varying(30),
    "first_name" character varying(150) NOT NULL,
    "last_name" character varying(150) NOT NULL,
    "date_joined" timestamptz NOT NULL,
    "email" character varying(254),
    "id_user" character varying(30) NOT NULL,
    "fullname" character varying(30),
    "location" character varying(30),
    "phone" character varying(30),
    "is_staff" boolean NOT NULL,
    "is_active" boolean NOT NULL,
    "client_id" character varying(255),
    CONSTRAINT "api_user_id_user_key" UNIQUE ("id_user"),
    CONSTRAINT "api_user_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "api_user_id_user_1361d29c_like" ON "public"."api_user" USING btree ("id_user");


DROP TABLE IF EXISTS "api_user_groups";
CREATE TABLE "public"."api_user_groups" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" bigint NOT NULL,
    "group_id" integer NOT NULL,
    CONSTRAINT "api_user_groups_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "api_user_groups_user_id_group_id_9c7ddfb5_uniq" UNIQUE ("user_id", "group_id")
) WITH (oids = false);

CREATE INDEX "api_user_groups_group_id_3af85785" ON "public"."api_user_groups" USING btree ("group_id");

CREATE INDEX "api_user_groups_user_id_a5ff39fa" ON "public"."api_user_groups" USING btree ("user_id");


DROP TABLE IF EXISTS "api_user_user_permissions";
CREATE TABLE "public"."api_user_user_permissions" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" bigint NOT NULL,
    "permission_id" integer NOT NULL,
    CONSTRAINT "api_user_user_permissions_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "api_user_user_permissions_user_id_permission_id_a06dd704_uniq" UNIQUE ("user_id", "permission_id")
) WITH (oids = false);

CREATE INDEX "api_user_user_permissions_permission_id_305b7fea" ON "public"."api_user_user_permissions" USING btree ("permission_id");

CREATE INDEX "api_user_user_permissions_user_id_f3945d65" ON "public"."api_user_user_permissions" USING btree ("user_id");


DROP TABLE IF EXISTS "auth_group";
CREATE TABLE "public"."auth_group" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" character varying(150) NOT NULL,
    CONSTRAINT "auth_group_name_key" UNIQUE ("name"),
    CONSTRAINT "auth_group_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "auth_group_name_a6ea08ec_like" ON "public"."auth_group" USING btree ("name");


DROP TABLE IF EXISTS "auth_group_permissions";
CREATE TABLE "public"."auth_group_permissions" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "group_id" integer NOT NULL,
    "permission_id" integer NOT NULL,
    CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id"),
    CONSTRAINT "auth_group_permissions_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "public"."auth_group_permissions" USING btree ("group_id");

CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "public"."auth_group_permissions" USING btree ("permission_id");


DROP TABLE IF EXISTS "auth_permission";
CREATE TABLE "public"."auth_permission" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" character varying(255) NOT NULL,
    "content_type_id" integer NOT NULL,
    "codename" character varying(100) NOT NULL,
    CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename"),
    CONSTRAINT "auth_permission_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "public"."auth_permission" USING btree ("content_type_id");

INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES
(1,	'Can add candidat',	1,	'add_candidat'),
(2,	'Can change candidat',	1,	'change_candidat'),
(3,	'Can delete candidat',	1,	'delete_candidat'),
(4,	'Can view candidat',	1,	'view_candidat'),
(5,	'Can add certificat',	2,	'add_certificat'),
(6,	'Can change certificat',	2,	'change_certificat'),
(7,	'Can delete certificat',	2,	'delete_certificat'),
(8,	'Can view certificat',	2,	'view_certificat'),
(9,	'Can add formation',	3,	'add_formation'),
(10,	'Can change formation',	3,	'change_formation'),
(11,	'Can delete formation',	3,	'delete_formation'),
(12,	'Can view formation',	3,	'view_formation'),
(13,	'Can add job',	4,	'add_job'),
(14,	'Can change job',	4,	'change_job'),
(15,	'Can delete job',	4,	'delete_job'),
(16,	'Can view job',	4,	'view_job'),
(17,	'Can add langue',	5,	'add_langue'),
(18,	'Can change langue',	5,	'change_langue'),
(19,	'Can delete langue',	5,	'delete_langue'),
(20,	'Can view langue',	5,	'view_langue'),
(21,	'Can add skills',	6,	'add_skills'),
(22,	'Can change skills',	6,	'change_skills'),
(23,	'Can delete skills',	6,	'delete_skills'),
(24,	'Can view skills',	6,	'view_skills'),
(25,	'Can add matching',	7,	'add_matching'),
(26,	'Can change matching',	7,	'change_matching'),
(27,	'Can delete matching',	7,	'delete_matching'),
(28,	'Can view matching',	7,	'view_matching'),
(29,	'Can add linkedin profile',	8,	'add_linkedinprofile'),
(30,	'Can change linkedin profile',	8,	'change_linkedinprofile'),
(31,	'Can delete linkedin profile',	8,	'delete_linkedinprofile'),
(32,	'Can view linkedin profile',	8,	'view_linkedinprofile'),
(33,	'Can add expprof',	9,	'add_expprof'),
(34,	'Can change expprof',	9,	'change_expprof'),
(35,	'Can delete expprof',	9,	'delete_expprof'),
(36,	'Can view expprof',	9,	'view_expprof'),
(37,	'Can add education',	10,	'add_education'),
(38,	'Can change education',	10,	'change_education'),
(39,	'Can delete education',	10,	'delete_education'),
(40,	'Can view education',	10,	'view_education'),
(41,	'Can add domaine',	11,	'add_domaine'),
(42,	'Can change domaine',	11,	'change_domaine'),
(43,	'Can delete domaine',	11,	'delete_domaine'),
(44,	'Can view domaine',	11,	'view_domaine'),
(45,	'Can add candidat has skills',	12,	'add_candidathasskills'),
(46,	'Can change candidat has skills',	12,	'change_candidathasskills'),
(47,	'Can delete candidat has skills',	12,	'delete_candidathasskills'),
(48,	'Can view candidat has skills',	12,	'view_candidathasskills'),
(49,	'Can add candidat has langue',	13,	'add_candidathaslangue'),
(50,	'Can change candidat has langue',	13,	'change_candidathaslangue'),
(51,	'Can delete candidat has langue',	13,	'delete_candidathaslangue'),
(52,	'Can view candidat has langue',	13,	'view_candidathaslangue'),
(53,	'Can add candidat has formation',	14,	'add_candidathasformation'),
(54,	'Can change candidat has formation',	14,	'change_candidathasformation'),
(55,	'Can delete candidat has formation',	14,	'delete_candidathasformation'),
(56,	'Can view candidat has formation',	14,	'view_candidathasformation'),
(57,	'Can add candidat has education',	15,	'add_candidathaseducation'),
(58,	'Can change candidat has education',	15,	'change_candidathaseducation'),
(59,	'Can delete candidat has education',	15,	'delete_candidathaseducation'),
(60,	'Can view candidat has education',	15,	'view_candidathaseducation'),
(61,	'Can add candidat has domaine',	16,	'add_candidathasdomaine'),
(62,	'Can change candidat has domaine',	16,	'change_candidathasdomaine'),
(63,	'Can delete candidat has domaine',	16,	'delete_candidathasdomaine'),
(64,	'Can view candidat has domaine',	16,	'view_candidathasdomaine'),
(65,	'Can add candidat has certificat',	17,	'add_candidathascertificat'),
(66,	'Can change candidat has certificat',	17,	'change_candidathascertificat'),
(67,	'Can delete candidat has certificat',	17,	'delete_candidathascertificat'),
(68,	'Can view candidat has certificat',	17,	'view_candidathascertificat'),
(69,	'Can add archived_candidat',	18,	'add_archived_candidat'),
(70,	'Can change archived_candidat',	18,	'change_archived_candidat'),
(71,	'Can delete archived_candidat',	18,	'delete_archived_candidat'),
(72,	'Can view archived_candidat',	18,	'view_archived_candidat'),
(73,	'Can add target client',	19,	'add_targetclient'),
(74,	'Can change target client',	19,	'change_targetclient'),
(75,	'Can delete target client',	19,	'delete_targetclient'),
(76,	'Can view target client',	19,	'view_targetclient'),
(77,	'Can add user',	20,	'add_user'),
(78,	'Can change user',	20,	'change_user'),
(79,	'Can delete user',	20,	'delete_user'),
(80,	'Can view user',	20,	'view_user'),
(81,	'Can add log entry',	21,	'add_logentry'),
(82,	'Can change log entry',	21,	'change_logentry'),
(83,	'Can delete log entry',	21,	'delete_logentry'),
(84,	'Can view log entry',	21,	'view_logentry'),
(85,	'Can add permission',	22,	'add_permission'),
(86,	'Can change permission',	22,	'change_permission'),
(87,	'Can delete permission',	22,	'delete_permission'),
(88,	'Can view permission',	22,	'view_permission'),
(89,	'Can add group',	23,	'add_group'),
(90,	'Can change group',	23,	'change_group'),
(91,	'Can delete group',	23,	'delete_group'),
(92,	'Can view group',	23,	'view_group'),
(93,	'Can add content type',	24,	'add_contenttype'),
(94,	'Can change content type',	24,	'change_contenttype'),
(95,	'Can delete content type',	24,	'delete_contenttype'),
(96,	'Can view content type',	24,	'view_contenttype'),
(97,	'Can add session',	25,	'add_session'),
(98,	'Can change session',	25,	'change_session'),
(99,	'Can delete session',	25,	'delete_session'),
(100,	'Can view session',	25,	'view_session'),
(101,	'Can add blacklisted token',	26,	'add_blacklistedtoken'),
(102,	'Can change blacklisted token',	26,	'change_blacklistedtoken'),
(103,	'Can delete blacklisted token',	26,	'delete_blacklistedtoken'),
(104,	'Can view blacklisted token',	26,	'view_blacklistedtoken'),
(105,	'Can add outstanding token',	27,	'add_outstandingtoken'),
(106,	'Can change outstanding token',	27,	'change_outstandingtoken'),
(107,	'Can delete outstanding token',	27,	'delete_outstandingtoken'),
(108,	'Can view outstanding token',	27,	'view_outstandingtoken');

DROP TABLE IF EXISTS "django_admin_log";
CREATE TABLE "public"."django_admin_log" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "action_time" timestamptz NOT NULL,
    "object_id" text,
    "object_repr" character varying(200) NOT NULL,
    "action_flag" smallint NOT NULL,
    "change_message" text NOT NULL,
    "content_type_id" integer,
    "user_id" bigint NOT NULL,
    CONSTRAINT "django_admin_log_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "public"."django_admin_log" USING btree ("content_type_id");

CREATE INDEX "django_admin_log_user_id_c564eba6" ON "public"."django_admin_log" USING btree ("user_id");


DROP TABLE IF EXISTS "django_content_type";
CREATE TABLE "public"."django_content_type" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "app_label" character varying(100) NOT NULL,
    "model" character varying(100) NOT NULL,
    CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model"),
    CONSTRAINT "django_content_type_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "django_migrations";
CREATE TABLE "public"."django_migrations" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "app" character varying(255) NOT NULL,
    "name" character varying(255) NOT NULL,
    "applied" timestamptz NOT NULL,
    CONSTRAINT "django_migrations_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "django_session";
CREATE TABLE "public"."django_session" (
    "session_key" character varying(40) NOT NULL,
    "session_data" text NOT NULL,
    "expire_date" timestamptz NOT NULL,
    CONSTRAINT "django_session_pkey" PRIMARY KEY ("session_key")
) WITH (oids = false);

CREATE INDEX "django_session_expire_date_a5c62663" ON "public"."django_session" USING btree ("expire_date");

CREATE INDEX "django_session_session_key_c0390e0f_like" ON "public"."django_session" USING btree ("session_key");


DROP TABLE IF EXISTS "token_blacklist_blacklistedtoken";
CREATE TABLE "public"."token_blacklist_blacklistedtoken" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "blacklisted_at" timestamptz NOT NULL,
    "token_id" bigint NOT NULL,
    CONSTRAINT "token_blacklist_blacklistedtoken_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "token_blacklist_blacklistedtoken_token_id_key" UNIQUE ("token_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "token_blacklist_outstandingtoken";
CREATE TABLE "public"."token_blacklist_outstandingtoken" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "token" text NOT NULL,
    "created_at" timestamptz,
    "expires_at" timestamptz NOT NULL,
    "user_id" bigint,
    "jti" character varying(255) NOT NULL,
    CONSTRAINT "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq" UNIQUE ("jti"),
    CONSTRAINT "token_blacklist_outstandingtoken_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like" ON "public"."token_blacklist_outstandingtoken" USING btree ("jti");

CREATE INDEX "token_blacklist_outstandingtoken_user_id_83bc629a" ON "public"."token_blacklist_outstandingtoken" USING btree ("user_id");


ALTER TABLE ONLY "public"."api_candidathascertificat" ADD CONSTRAINT "api_candidathascerti_id_candidat_377eaed7_fk_api_candi" FOREIGN KEY (id_candidat) REFERENCES api_candidat(id_candidat) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE ONLY "public"."api_candidathascertificat" ADD CONSTRAINT "api_candidathascerti_id_certificat_f1c90784_fk_api_certi" FOREIGN KEY (id_certificat) REFERENCES api_certificat(id_certificat) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ONLY "public"."api_candidathasdomaine" ADD CONSTRAINT "api_candidathasdomai_id_candidat_2afb0b54_fk_api_candi" FOREIGN KEY (id_candidat) REFERENCES api_candidat(id_candidat) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE ONLY "public"."api_candidathasdomaine" ADD CONSTRAINT "api_candidathasdomai_id_domaine_f4c88203_fk_api_domai" FOREIGN KEY (id_domaine) REFERENCES api_domaine(id_domaine) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ONLY "public"."api_candidathaseducation" ADD CONSTRAINT "api_candidathaseduca_id_candidat_19931e11_fk_api_candi" FOREIGN KEY (id_candidat) REFERENCES api_candidat(id_candidat) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE ONLY "public"."api_candidathaseducation" ADD CONSTRAINT "api_candidathaseduca_id_education_8cbbfbe8_fk_api_educa" FOREIGN KEY (id_education) REFERENCES api_education(id_education) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ONLY "public"."api_candidathasformation" ADD CONSTRAINT "api_candidathasforma_id_candidat_f0dcb740_fk_api_candi" FOREIGN KEY (id_candidat) REFERENCES api_candidat(id_candidat) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE ONLY "public"."api_candidathasformation" ADD CONSTRAINT "api_candidathasforma_id_formation_ccc859a3_fk_api_forma" FOREIGN KEY (id_formation) REFERENCES api_formation(id_formation) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ONLY "public"."api_candidathaslangue" ADD CONSTRAINT "api_candidathaslangu_id_candidat_e6b042c1_fk_api_candi" FOREIGN KEY (id_candidat) REFERENCES api_candidat(id_candidat) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE ONLY "public"."api_candidathaslangue" ADD CONSTRAINT "api_candidathaslangu_id_langue_c90e0d1f_fk_api_langu" FOREIGN KEY (id_langue) REFERENCES api_langue(id_langue) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ONLY "public"."api_candidathasskills" ADD CONSTRAINT "api_candidathasskill_id_candidat_97c63b55_fk_api_candi" FOREIGN KEY (id_candidat) REFERENCES api_candidat(id_candidat) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE ONLY "public"."api_candidathasskills" ADD CONSTRAINT "api_candidathasskill_id_skills_f610e66e_fk_api_skill" FOREIGN KEY (id_skills) REFERENCES api_skills(id_skills) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ONLY "public"."api_expprof" ADD CONSTRAINT "api_expprof_id_candidat_22fc432a_fk_api_candidat_id_candidat" FOREIGN KEY (id_candidat) REFERENCES api_candidat(id_candidat) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ONLY "public"."api_job" ADD CONSTRAINT "api_job_target_client_id_99ae746e_fk_api_targetclient_id" FOREIGN KEY (target_client_id) REFERENCES api_targetclient(id) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ONLY "public"."api_matching" ADD CONSTRAINT "api_matching_id_candidat_id_b3af4aaa_fk_api_candi" FOREIGN KEY (id_candidat_id) REFERENCES api_candidat(id_candidat) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE ONLY "public"."api_matching" ADD CONSTRAINT "api_matching_id_job_id_d7c43168_fk_api_job_id" FOREIGN KEY (id_job_id) REFERENCES api_job(id) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ONLY "public"."api_user_groups" ADD CONSTRAINT "api_user_groups_group_id_3af85785_fk_auth_group_id" FOREIGN KEY (group_id) REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE ONLY "public"."api_user_groups" ADD CONSTRAINT "api_user_groups_user_id_a5ff39fa_fk_api_user_id" FOREIGN KEY (user_id) REFERENCES api_user(id) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ONLY "public"."api_user_user_permissions" ADD CONSTRAINT "api_user_user_permis_permission_id_305b7fea_fk_auth_perm" FOREIGN KEY (permission_id) REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE ONLY "public"."api_user_user_permissions" ADD CONSTRAINT "api_user_user_permissions_user_id_f3945d65_fk_api_user_id" FOREIGN KEY (user_id) REFERENCES api_user(id) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ONLY "public"."auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY (permission_id) REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE ONLY "public"."auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY (group_id) REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ONLY "public"."auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ONLY "public"."django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ONLY "public"."token_blacklist_blacklistedtoken" ADD CONSTRAINT "token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk" FOREIGN KEY (token_id) REFERENCES token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE ONLY "public"."token_blacklist_outstandingtoken" ADD CONSTRAINT "token_blacklist_outs_user_id_83bc629a_fk_api_user_" FOREIGN KEY (user_id) REFERENCES api_user(id) DEFERRABLE INITIALLY DEFERRED DEFERRABLE;

-- 2025-03-11 12:24:02.6567+00
