"""
Django settings for get_talent project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
""" 
 
import os    
from pathlib import Path                                                                  


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'                
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'get_talent/static'),
]
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1(iq9t)5^fegip2$3!l7br_(z)h8n4$lk5o9ohz)u*-zyv$oe)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Define config variables 
HOST_FRONT = os.environ.get("HOST_FRONT", "")  
HOST_BACK_CV = os.environ.get("HOST_BACK_CV", "") 
HOST_BACK_LINKEDIN = os.environ.get("HOST_BACK_LINKEDIN", "")
#HOST_OWNCLOUD = os.environ.get("HOST_OWNCLOUD", "")

PREFIX = 'https://'  
CORS_HOST_FRONT = PREFIX + os.environ.get("HOST_FRONT", "")
CORS_HOST_BACK_CV = PREFIX + os.environ.get("HOST_BACK_CV", "")
CORS_HOST_BACK_LINKEDIN = PREFIX + os.environ.get("HOST_BACK_LINKEDIN", "")
#CORS_HOST_OWNCLOUD = PREFIX + os.environ.get("HOST_OWNCLOUD", "")

ALLOWED_HOSTS = ['*']
#ALLOWED_HOSTS = ["127.0.0.1", "localhost", "http://chromeDriver:4444", HOST_FRONT, HOST_BACK_CV, HOST_BACK_LINKEDIN,
#                 '13.36.69.52']
CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = ["http://127.0.0.1:4200", "http://localhost:4200", "http://chromeDriver:4444",
			 "http://127.0.0.1:8000", "http://localhost:8000",     
                        CORS_HOST_FRONT, CORS_HOST_BACK_CV, CORS_HOST_BACK_LINKEDIN]
CSRF_TRUSTED_ORIGINS = ['http://localhost']
# Application definition
#python manage.py migrate
INSTALLED_APPS = [
    'rest_framework',
    'api',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
     'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'get_talent.middleware.RequestMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
	
]

ROOT_URLCONF = 'get_talent.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'get_talent.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3', 
    }               
}

DATABASES = {
    'default': {
    
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5435"),    
    }
}

AUTH_USER_MODEL = 'api.User'

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

...

# apiexample/settings.py
AUTH0_DOMAIN = os.environ.get("AUTH0_DOMAIN", "") 
API_IDENTIFIER = os.environ.get("API_IDENTIFIER", "") 
AUTH0_CLIENT_ID=os.environ.get("AUTH0_CLIENT_ID", "") 
AUTH0_CLIENT_SECRET=os.environ.get("AUTH0_CLIENT_SECRET", "") 
# JWT_AUTH = {
#     'JWT_PAYLOAD_GET_USERNAME_HANDLER':
#         'auth0authorization.utils.jwt_get_username_from_payload_handler',
#     'JWT_DECODE_HANDLER':
#         'auth0authorization.utils.jwt_decode_token',
#     'JWT_ALGORITHM': 'RS256',
#     'JWT_AUDIENCE': API_IDENTIFIER,
#     'JWT_ISSUER': AUTH0_DOMAIN,
#     'JWT_AUTH_HEADER_PREFIX': 'Bearer',
# }

# apiexample/settings.py

# REST_FRAMEWORK = {
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated',
#     ),
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework.authentication.SessionAuthentication',
#         'rest_framework.authentication.BasicAuthentication',
#     ),
# }
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "get_talent.auth0backend.Auth0Authentication",  # Custom authentication class
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = False
# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

 
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

