# Generated by Django 4.1.4 on 2024-11-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_targetclient_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salaire_maximum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salaire_minimum',
            field=models.FloatField(null=True),
        ),
    ]
