# Generated by Django 4.1.4 on 2024-12-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_job_location_job_salaire_maximum_job_salaire_minimum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matching',
            old_name='note',
            new_name='note_dg',
        ),
        migrations.AddField(
            model_name='matching',
            name='note_rh',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='note_technique',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='note_test_technique',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
