# Generated by Django 4.1.4 on 2024-12-18 09:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_fullname_user_location_user_phone'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='archived_candidat',
            name='unique_archive',
        ),
        migrations.RenameField(
            model_name='archived_candidat',
            old_name='date_insertion',
            new_name='datenaissance',
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='certificat',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client'),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='domain',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=254, null=True), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='education',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='embedding_cohere',
            field=pgvector.django.VectorField(dimensions=4096, null=True),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='first_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='formation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='langues',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), default=list, size=None),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='nbrexp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='pays_de_residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='phone',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='poste_actuelle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='sexe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='source',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='archived_candidat',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='archived_candidat',
            unique_together={('id', 'client')},
        ),
        migrations.RemoveField(
            model_name='archived_candidat',
            name='id_candidat',
        ),
    ]
