# Generated by Django 4.1.4 on 2024-12-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_archived_candidat_unique_archive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archived_candidat',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='archived_candidat',
            name='status',
        ),
    ]
