# Generated by Django 4.1.4 on 2025-03-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_candidat_archived_candidat_archived_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='archived_candidat',
            name='client',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='client',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domaine',
            name='client',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkedinprofile',
            name='client',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matching',
            name='client',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetclient',
            name='client',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
