# Generated by Django 4.1.4 on 2025-03-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_user_client_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidat',
            old_name='client',
            new_name='client_id',
        ),
        migrations.AlterUniqueTogether(
            name='candidat',
            unique_together={('id_candidat', 'client_id')},
        ),
    ]
