# Generated by Django 4.1.4 on 2025-03-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_client_candidat_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matching',
            name='unique_matching',
        ),
        migrations.RenameField(
            model_name='archived_candidat',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='domaine',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='linkedinprofile',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='targetclient',
            old_name='client',
            new_name='client_id',
        ),
        migrations.AlterUniqueTogether(
            name='archived_candidat',
            unique_together={('id', 'client_id')},
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('file_name', 'destination', 'client_id')},
        ),
        migrations.AlterUniqueTogether(
            name='linkedinprofile',
            unique_together={('id_profile', 'client_id')},
        ),
        migrations.AddConstraint(
            model_name='matching',
            constraint=models.UniqueConstraint(fields=('id_candidat', 'id_job', 'client_id'), name='unique_matching'),
        ),
    ]
