# Generated by Django 4.1.4 on 2025-03-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
