# Generated by Django 4.1.4 on 2025-03-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_user_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='education',
            unique_together={('nom_ecole', 'nom_diplome', 'type_diplome', 'specialite')},
        ),
    ]
