# Generated by Django 4.1.4 on 2025-03-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_education_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificat',
            name='nom_certificat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='certificat',
            unique_together={('nom_certificat', 'domaine', 'duree', 'organisation')},
        ),
        migrations.AlterUniqueTogether(
            name='expprof',
            unique_together={('date', 'titre_prof', 'nom_societe', 'poste', 'description', 'technos')},
        ),
        migrations.AlterUniqueTogether(
            name='formation',
            unique_together={('nom_formation', 'duree_formation')},
        ),
    ]
